version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1ASydneycrescent$!
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: always

  api:
    build: .
    container_name: tradeplatform_api
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__devConnection=Server=sqlserver,1433;Database=tds-main;User ID=sa;Password=1ASydneycrescent$!;Encrypt=False;
    ports:
      - "5000:5000"
    restart: always

volumes:
  sql_data:
