<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
  <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	
  </PropertyGroup>
  <ItemGroup>
   <None Update="appsettings.json">
    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    <CopyToPublishDirectory>Never</CopyToPublishDirectory>
  </None>

  <None Update="appsettings.Production.json">
    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    <CopyToPublishDirectory>Never</CopyToPublishDirectory>
  </None>

  <Content Update="web.config">
    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    <CopyToPublishDirectory>Never</CopyToPublishDirectory>
  </Content>
  
  <Content Update="appsettings*.json" CopyToOutputDirectory="Never" />
  <Content Update="web.config" CopyToOutputDirectory="Never" />
  <None Remove="TradePlatform.Api" />

  <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.4.4" />
   
  <PackageReference Include="AWSSDK.S3" Version="4.0.24.1" />
   
  <PackageReference Include="Azure.AI.Vision.ImageAnalysis" Version="1.0.0" />
   
  <PackageReference Include="Azure.Storage.Blobs" Version="12.27.0" />
   
  <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
   
  <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
   
  <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.0" />
   
  <PackageReference Include="Microsoft.Data.SqlClient" Version="5.1.5" />
  <PackageReference Include="Microsoft.Data.SqlClient.SNI.runtime" Version="5.1.5" />

    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Dapper" Version="2.1.72" />
    <PackageReference Include="Stripe.net" Version="51.2.0-beta.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.1" />
  </ItemGroup>

</Project>
