name: Deploy TradePlatform.Api to Windows EC2 (IIS)

on:
  workflow_dispatch:  
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore TradePlatform.Api.csproj

      - name: Clean previous builds
        run: dotnet clean TradePlatform.Api.csproj -c Release

      - name: Publish for Windows IIS
        run: dotnet publish TradePlatform.Api.csproj -c Release -o publish --runtime win-x64 --no-self-contained /p:UseAppHost=false

      - name: Zip publish folder
        run: Compress-Archive -Path publish -DestinationPath publish.zip -Force

      - name: Copy files to EC2 via WinRM
        run: |
          $session = New-PSSession -ComputerName $env:WIN_EC2_HOST -Credential (New-Object System.Management.Automation.PSCredential($env:WIN_EC2_USER,(ConvertTo-SecureString $env:WIN_EC2_PASS -AsPlainText -Force))) -UseSSL -SessionOption (New-PSSessionOption -SkipCACheck -SkipCNCheck)
          Copy-Item -Path publish.zip -Destination "C:\deploy-temp\publish.zip" -ToSession $session -Force

      - name: Deploy on EC2 via WinRM
        run: |
          $session = New-PSSession -ComputerName $env:WIN_EC2_HOST -Credential (New-Object System.Management.Automation.PSCredential($env:WIN_EC2_USER,(ConvertTo-SecureString $env:WIN_EC2_PASS -AsPlainText -Force))) -UseSSL -SessionOption (New-PSSessionOption -SkipCACheck -SkipCNCheck)

          Invoke-Command -Session $session -ScriptBlock {
            $LIVE = $env:WIN_IIS_PATH
            $TEMP = "C:\deploy-temp\publish"
            $BACKUP = "C:\deploy-backup"
            $ZIP = "C:\deploy-temp\publish.zip"
            $APPPOOL = $env:WIN_IIS_APPPOOL

            Remove-Item -Recurse -Force $TEMP -ErrorAction SilentlyContinue
            Expand-Archive -Path $ZIP -DestinationPath "C:\deploy-temp" -Force

            Import-Module WebAdministration
            Stop-WebAppPool $APPPOOL

            Remove-Item -Recurse -Force $BACKUP -ErrorAction SilentlyContinue
            if (Test-Path $LIVE) { Move-Item $LIVE $BACKUP }

            Move-Item $TEMP $LIVE

            Start-WebAppPool $APPPOOL
            Remove-Item $ZIP -Force
          }
