name: Backend Stage Deploy

on:
  workflow_dispatch:

jobs:
  stage:
    uses: ./.github/workflows/deploy-service.yml
    with:
      environment: staging
      target_path: 'C:\Deployments\MyTradesShop\Stage\Backend'
      app_pool_name: 'TradesShopServiceStage'
    secrets: inherit