name: Backend Live Deploy

on:
  workflow_dispatch:

jobs:
  live:
    uses: ./.github/workflows/deploy-service.yml
    with:
      environment: production
      target_path: 'C:\Deployments\MyTradesShop\Live\Backend'
      app_pool_name: 'MyTradesShopBackendLive'
    secrets: inherit